version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq
  rake:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
    command: bundle exec rake binance_price_fetch:start
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"